<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="G1C2ML14375" name="com.bookmyroom.testng.ApplicationTest" tests="5" failures="0" timestamp="06 Sep 2018 05:17:01 GMT" time="26.263" errors="1">
  <testcase name="signUpTest" time="0.105" classname="com.bookmyroom.testng.ApplicationTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.bookmyroom.util.Reusable.navigateTo(Reusable.java:37)
at com.bookmyroom.pages.SignUpPage.signUp(SignUpPage.java:42)
at com.bookmyroom.testng.ApplicationTest.signUpTest(ApplicationTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- signUpTest -->
  <testcase name="signUpTest" time="4.075" classname="com.bookmyroom.testng.ApplicationTest"/>
  <testcase name="signUpTest" time="3.396" classname="com.bookmyroom.testng.ApplicationTest"/>
  <testcase name="signUpTest" time="3.880" classname="com.bookmyroom.testng.ApplicationTest"/>
  <testcase name="signUpTest" time="14.807" classname="com.bookmyroom.testng.ApplicationTest"/>
</testsuite> <!-- com.bookmyroom.testng.ApplicationTest -->
